# Configurações do Resilience4j - Retry
resilience4j.retry.instances.telemetriaService.maxAttempts=3
resilience4j.retry.instances.telemetriaService.waitDuration=2s
resilience4j.retry.instances.telemetriaService.enableExponentialBackoff=true
resilience4j.retry.instances.telemetriaService.exponentialBackoffMultiplier=2